### ISSUE TITLE
Collisions are not created correctly if we set a single tile at the right side of the level.

### ISSUE THREAD

**Issue by divby00** [levigilbert/godot-LDtk-import#15]
LDtk version: 1.1.3
Godot version 3.5.rc5 (also happens in 3.4.4 stable)
Hi, I have found some issue setting a level with a single tile width at the right of the level. This level for example:
![imagen](https://user-images.githubusercontent.com/7277786/177099608-41cd5e64-6715-42f7-b28e-c6cd0976dd5f.png)
If you import it, you will get these collisions:
![imagen](https://user-images.githubusercontent.com/7277786/177099730-1761c9b3-25bf-444d-905a-f5083023382d.png)
I have added a few prints to try to understand what is happening and I have found that looks like initial_position is not being calculated correctly for the case where there's a single tile:
![imagen](https://user-images.githubusercontent.com/7277786/177100418-52cccca2-46ae-4e11-b819-d7376cbc8e6d.png)
If I add one more tile the issue is gone:
![imagen](https://user-images.githubusercontent.com/7277786/177100653-2d8549ae-4fd9-4c3b-8252-74dc1a21cdaa.png)
The issue happens as well if there isn't any tile at the beginning of the row:
![imagen](https://user-images.githubusercontent.com/7277786/177100814-cff8c0ca-cd1f-4d99-8b67-c8d12815641e.png)

**Comment by levigilbert** [comment]
Just updated the plugin, this should be working correctly now.

**Comment by divby00** [comment]
Hi, thanks for the plugin and the quick reply ;-)
Unfortunately, looks like this is still failing for the simple box use case:

Importing this map:
![imagen](https://user-images.githubusercontent.com/7277786/177255666-f2f86a55-3680-42b7-bef4-57ce6bcb2a2f.png)

Will give the following result:
![imagen](https://user-images.githubusercontent.com/7277786/177255715-a135afd3-3ebc-45f5-97a4-f5460d658149.png)

Minimum project to reproduce the issue:
[LDtkImporterTest.zip](https://github.com/levigilbert/godot-LDtk-import/files/9043473/LDtkImporterTest.zip)

**Comment by levigilbert** [comment]
Hey, thanks for letting me know it still wasn't working. Forgot to change a
variable while I was testing, but it should be fixed now.

Let me know if it works on your end.
- Levi

**Comment by divby00** [comment]
Hi Levi, I have tested it with both the testing project and my current project and now it's working as expected!, Thanks a lot!

**Comment by levigilbert** [comment]
Great, glad to hear it! I just found another bug with the collision import
and just uploaded it a little bit ago so you might want to grab the
latest version.

Thanks,
-Levi

**Comment by divby00** [comment]
Updated! thanks for letting me know ;-)
Regards
